### ISSUE TITLE
NPE while initializing Container Entry in Viewer.

### ISSUE THREAD

**Issue by biswardas** [biswardas/event-plus#12]
12:19:50 WARNING com.biswa.ep.entities.ContainerTask run:Exception occured in thread:AWT-EventQueue-0 
java.lang.NullPointerException
	at com.biswa.ep.entities.store.ConcreteContainerEntry.<init>(ConcreteContainerEntry.java:49)
	at com.biswa.ep.entities.store.ConcreteContainerEntry.<init>(ConcreteContainerEntry.java:28)
	at com.biswa.ep.entities.store.ConcreteContainerEntryStore.getDefaultEntry(ConcreteContainerEntryStore.java:27)
	at com.biswa.ep.entities.ConcreteContainer.getDefaultEntry(ConcreteContainer.java:207)
	at com.biswa.ep.entities.CascadeContainer.reComputeDefaultValues(CascadeContainer.java:571)
	at com.biswa.ep.entities.CascadeContainer.connected(CascadeContainer.java:560)
	at com.biswa.ep.util.AbstractViewer.connected(AbstractViewer.java:35)
	at com.biswa.ep.entities.transaction.Agent$9$1.runtask(Agent.java:297)
	at com.biswa.ep.entities.ContainerTask.run(ContainerTask.java:61)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by biswardas** [comment]
Interesting AWT-EventQueue thread is recreating and threadlocals are getting lost. Taking a step back it appears the TransactionAdapter should never have known about Swing or Otherwise taking thread off. Letting transaction threads directly interacting with UI object however thats not a concern at this point.
